FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
ARG LLVM_VERSION=13
ARG OMNETPP_VERSION=6.0.1
ARG PYTHON_VERSION=3.9

COPY ./install.sh /root/install.sh
RUN /root/install.sh dev

WORKDIR /root
RUN arch=$(arch) && \
    wget https://github.com/omnetpp/omnetpp/releases/download/omnetpp-${OMNETPP_VERSION}/omnetpp-${OMNETPP_VERSION}-linux-${arch}.tgz \
    --referer=https://omnetpp.org/ -O omnetpp-src-linux.tgz --progress=dot:giga && \
    tar xf omnetpp-src-linux.tgz && rm omnetpp-src-linux.tgz
RUN mv omnetpp-${OMNETPP_VERSION} omnetpp
WORKDIR /root/omnetpp
ENV PATH /root/omnetpp/bin:$PATH
RUN mkdir -p /root/omnetpp
WORKDIR /root/omnetpp

RUN bash -c "source setenv && \
    ./configure WITH_OSG=no WITH_QTENV=yes && \
    make -j $(nproc) MODE=debug base && \
    make -j $(nproc) MODE=release base && \
    rm -r out"

WORKDIR /root
ENV HOME=/root/
CMD /bin/bash --init-file /root/.bashrc
ENV OMNETPP_DOCKERFILE_VERSION=0.9.6
