
FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
ARG LLVM_VERSION=13
ARG OMNETPP_VERSION=6.0
ARG PYTHON_VERSION=3.9

RUN apt-get update -y && apt-get install -y --no-install-recommends  \
    cmake software-properties-common wget bison flex make git software-properties-common gpg gpg-agent build-essential time lcov\
    clang-format-${LLVM_VERSION} clang-tidy-${LLVM_VERSION} lldb-${LLVM_VERSION} \
    qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools libqt5opengl5-dev libgtk-3-0 default-jre vim tig \
    && ln -s /usr/bin/clang-format-${LLVM_VERSION} /usr/bin/clang-format \
    && ln -s /usr/bin/clang-tidy-${LLVM_VERSION} /usr/bin/clang-tidy \
    && ln -sf /usr/bin/clang-${LLVM_VERSION} /usr/bin/clang \
    && ln -sf /usr/bin/clang++-${LLVM_VERSION} /usr/bin/clang++ \
    && ln -sf /usr/bin/llvm-profdata-${LLVM_VERSION} /usr/bin/llvm-profdata \
    && ln -sf /usr/bin/llvm-cov-${LLVM_VERSION} /usr/bin/llvm-cov \
    && wget -q -O - https://dl.google.com/linux/linux_signing_key.pub --progress=dot:giga | apt-key add - \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update -y \
    && apt-get install -y --no-install-recommends \
    python${PYTHON_VERSION} \
    python${PYTHON_VERSION}-dev \
    libpython${PYTHON_VERSION}-dev \
    python${PYTHON_VERSION}-distutils \
    && wget https://bootstrap.pypa.io/get-pip.py --progress=dot:giga  \
    && python${PYTHON_VERSION} ./get-pip.py \
    && rm get-pip.py \
    && pip${PYTHON_VERSION} install numpy scipy pandas matplotlib posix_ipc \
    && ln -s /usr/bin/python${PYTHON_VERSION}  /usr/local/bin/python \
    && ln -s /usr/bin/python${PYTHON_VERSION}  /usr/local/bin/python3 \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -r /var/lib/apt/lists/*

WORKDIR /root
RUN wget https://github.com/omnetpp/omnetpp/releases/download/omnetpp-${OMNETPP_VERSION}/omnetpp-${OMNETPP_VERSION}-linux-x86_64.tgz \
    --referer=https://omnetpp.org/ -O omnetpp-src-linux.tgz --progress=dot:giga && \
    tar xf omnetpp-src-linux.tgz && rm omnetpp-src-linux.tgz
RUN mv omnetpp-${OMNETPP_VERSION} omnetpp
WORKDIR /root/omnetpp
ENV PATH /root/omnetpp/bin:$PATH
RUN mkdir -p /root/omnetpp
WORKDIR /root/omnetpp

RUN bash -c "source setenv && \
    ./configure WITH_OSG=no WITH_QTENV=yes && \
    make -j $(nproc) MODE=debug base && \
    make -j $(nproc) MODE=release base && \
    rm -r out"

WORKDIR /root
ENV HOME=/root/
CMD /bin/bash --init-file /root/.bashrc
