name: docker build
on: [push]
jobs:
  build-dev-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: actions/github-script@v6
        id: ref-name
        with:
          script: |
            return "${{github.ref_name}}".trim().replaceAll("/", "-")
          result-encoding: string
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push dev image
        uses: docker/build-push-action@v5
        with:
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile.dev
          tags: |
            ghcr.io/${{ github.repository_owner }}/quisp:latest
            ghcr.io/${{ github.repository_owner }}/quisp:${{ steps.ref-name.outputs.result }}
            ghcr.io/${{ github.repository_owner }}/quisp:${{ github.sha }}
  build-ci-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: actions/github-script@v6
        id: ref-name
        with:
          script: |
            return "${{github.ref_name}}".trim().replaceAll("/", "-")
          result-encoding: string
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push ci image
        uses: docker/build-push-action@v5
        with:
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile.ci
          tags: |
            ghcr.io/${{ github.repository_owner }}/quisp-ci:latest
            ghcr.io/${{ github.repository_owner }}/quisp-ci:${{ steps.ref-name.outputs.result }}
            ghcr.io/${{ github.repository_owner }}/quisp-ci:${{ github.sha }}
  build-devcontainer-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: actions/github-script@v6
        id: ref-name
        with:
          script: |
            return "${{github.ref_name}}".trim().replaceAll("/", "-")
          result-encoding: string
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push devcontainer image
        uses: docker/build-push-action@v5
        with:
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile.devcontainer
          tags: |
            ghcr.io/${{ github.repository_owner }}/quisp-dev:latest
            ghcr.io/${{ github.repository_owner }}/quisp-dev:${{ steps.ref-name.outputs.result }}
            ghcr.io/${{ github.repository_owner }}/quisp-dev:${{ github.sha }}
